"""some migration

Revision ID: b218f122b8c1
Revises: 75a9cb275b31
Create Date: 2025-11-17 02:48:27.206197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b218f122b8c1'
down_revision = '75a9cb275b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
